<?php

/**
 * @file
 * Contains survey_manager.module..
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function survey_manager_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === "help.page.survey_manager") {
    $output = '<p>' . t('Manage third-party surveys.') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_page_bottom().
 */
function survey_manager_page_bottom(array &$page_bottom) {
  $surveys                       = _survey_manager_get_surveys('survey_embed_code_block');

  foreach ($surveys as $block) {
    // Check this answer http://drupal.stackexchange.com/a/185691/23477 .
    if ($block->access('view')) {
      $page_bottom['survey_manager'][] = ['#markup' => $block->get('settings')['embed_code'], '#allowed_tags' => ['script']];
    }
  }
}

/**
 * Get list of survey blocks by type.
 *
 * @return array
 *   Array of survey blocks.
 */
function _survey_manager_get_surveys($survey_plugin_id) {
  $query      = \Drupal::entityQuery('block')
    ->condition('plugin', $survey_plugin_id);
  $survey_ids = $query->execute();
  $surveys    = Block::loadMultiple($survey_ids);

  return $surveys;
}

/**
 * Implements hook_form_alter().
 */
function survey_manager_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  if ($form_id == "block_admin_display_form") {
    foreach ($form['blocks'] as $key => $block) {
      if (!empty($block['operations']['#links']['edit']['url'])) {
        $block_plugin_id = $block['operations']['#links']['edit']['url']->getOptions()['entity']->getPluginId();
        if ($block_plugin_id == 'survey_embed_code_block') {
          unset($form['blocks'][$key]);
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function survey_manager_theme($existing, $type, $theme, $path) {
  return array(
    'surveys_list' => array(
      'variables' => array(
        'surveys' => NULL,
      ),
    ),
  );
}
