survey_manager.survey.*:
  type: config_entity
  label: 'Survey'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Title'
    type:
      type: string
      label: 'Type'
    code:
      type: text
      label: 'HTML code'
    visibility:
      type: mapping
      label: 'Visibility'